### ISSUE TITLE
Auto rotate again..

### ISSUE THREAD

**Issue by armaustin** [SamSprung/SamSprung-TooUI#16]
Still having issues with this app continuously turning on Auto Rotate every single time I close the phone.  The auto rotate toggle on the doesn't appear to do anything.
Question: is there any good reason why this app would even need to have the auto rotate toggle button, or could it just be removed completely?

**Comment by armaustin** [comment]
And yes I just updated to latest version. I really like now that you can use the logo back button to get back to standard clock and widgets.

**Comment by AbandonedCart** [comment]
The infamous struggle of one person wanting it added, another wanting it removed.

**Comment by AbandonedCart** [comment]
Just to clear up what seems like a misunderstanding, the toggle has NOTHING to do with your issue. The issue is that the cover is locked in landscape. It is made to not view portrait apps at all. To rectify that (because it is a SHIT STORM when portrait apps don't work), the things that make a phone respect a set orientation (namely, the rotation lock) has to be disabled so the app can force the cover screen to think it has always been in portrait and allow the apps to launch. It's a very unstable ecosystem that involves a lot of workarounds. Understandably, that comes with a lot of people thinking I am an idiot because it should work and it doesn't always because "why would Samsung go and intentionally break the functionality?" Good question...

**Comment by armaustin** [comment]
FYI I wasn't trying to disrespect you, just trying to provide some feedback of issues. This is a really great application and I want it to be even better..thanks for your hard work :)

**Comment by AbandonedCart** [comment]
I didn't take offense. It is one of those things that seems like it should be a lot simpler than it is because of some irrational restrictions.
