### ISSUE TITLE
Drawer app icons too small

### ISSUE THREAD

**Issue by kariyna** [SamSprung/SamSprung-TooUI#209]
It's hard to see apps in the app drawer, please make it so we can adjust the size of them. Also it would be good if we can completely disable some features we don't need, like the notification centre and the bottom status/time bar.

**Comment by AbandonedCart** [comment]
There is currently no way to make the icons resizeable without rewriting the entire launcher, but it is something that is being considered for future versions. You can disable notifications by not granting notification permission. The bottom bar contains the quick toggles and rotation lock, so disabling that would also remove all of those features. Unfortunately, those were something that was **heavily** requested and are not going to be removed.

**Comment by kariyna** [comment]
Disabling notification permissions worked. Please consider the icon resize for the next version it would be an invaluable addition. As for the button bar I totally understand not removing it completely, if a toggle is possible to hide it or show it or put the transparancy to 100 that would work just fine.

**Comment by AbandonedCart** [comment]
You might want to consider the Good Lock launcher. It is another option that offers up to 5 apps that can be configured as a widget. It has no additional functionality, so there is nothing to disable.

I also put out some requests for feedback to get an idea of what the general opinion was about the icon sizes. Making them resize is a bit of a can of worms, since this is a much smaller screen than the default. Leaving it to the user will be a range of roughly 40 to 60, which realistically isn't as much as it seems. It can only be even numbers, so that is about 10 steps that only make up the difference of the size of a single letter in this post.

**Comment by kariyna** [comment]
Good Lock/Nice Lock worked flawlessly. Thank you.
