### ISSUE TITLE
Forcing other orientations

### ISSUE THREAD

**Issue by amg-12** [SamSprung/SamSprung-TooUI#233]
I want to run apps in reverse landscape orientation. I attempted to do this by modifying the following line in [LauncherManager](https://github.com/SamSprung/SamSprung-TooUI/blob/launcher/app/src/main/java/com/eightbit/samsprung/drawer/LauncherManager.kt):

`orientationLock.addOrientationLayout(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT)`

I was able to force some apps into reverse portrait orientation by changing the value to `SCREEN_ORIENTATION_REVERSE_PORTRAIT`. However, setting the value to `SCREEN_ORIENTATION_REVERSE_LANDSCAPE` only forces apps into regular landscape, and not reverse landscape.

Can you please help me understand how to get this to work?

**Comment by AbandonedCart** [comment]
It's possible that the firmware is the issue. A lot of the irrational limitations are Samsung and OPPO designing the stock launcher with very specific plans for how it will be used.

**Comment by amg-12** [comment]
Can you think of any other way to test whether this is possible within the firmware? (I'm using a Samsung Flip3 btw)

**Comment by AbandonedCart** [comment]
`adb shell wm user-rotation [-d DISPLAY_ID] [free|lock] [rotation]`

So reverse landscape would be `wm user-rotation -d 1 lock 2`

After a few tests, it seems there is no automatic rotation for the cover. That means there is something setting a similar command (likely in the build.prop or display configuration file). If you want to reset the rotation, you would need to run `wm user-rotation -d 1 lock 0` because setting free has no effect.

**Comment by amg-12** [comment]
Thank you so much for your help!! That solution works perfectly for me! 😄 I've been trying to do this for a really long time.
